# Generated by Django 3.2.7 on 2023-03-18 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('home_description', models.TextField()),
                ('rent_price', models.IntegerField()),
                ('total_square_feet', models.IntegerField()),
                ('total_washroom', models.IntegerField()),
                ('total_bed', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('division', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong')], max_length=50)),
                ('district', models.CharField(choices=[('Gec Moor', 'Gec Moor'), ('Chawkbazar', 'Chawkbazar'), ('mirpur', 'Mirpur'), ('Gulshan', 'Gulshan')], max_length=1000)),
                ('home_image_one', models.ImageField(upload_to='images/')),
                ('home_image_two', models.ImageField(upload_to='images/')),
                ('home_image_three', models.ImageField(upload_to='images/')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
