# Generated by Django 3.2.7 on 2023-03-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='user',
        ),
    ]
