# Generated by Django 3.2.7 on 2023-03-24 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_auth', '0003_rent_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('division', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong')], max_length=50)),
                ('district', models.CharField(choices=[('Gec Moor', 'Gec Moor'), ('Chawkbazar', 'Chawkbazar'), ('mirpur', 'Mirpur'), ('Gulshan', 'Gulshan')], max_length=1000)),
                ('details_address', models.TextField()),
                ('educations_details', models.TextField()),
                ('teacher_image', models.ImageField(upload_to='images/')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
