# Generated by Django 4.1.3 on 2023-05-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_rentcomment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tution',
            name='tution_image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
