# Generated by Django 4.2.1 on 2023-05-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0010_tution_tution_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
