# Generated by Django 4.2.1 on 2023-05-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0013_rentpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentpayment',
            name='payment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
