# Generated by Django 4.2.1 on 2023-05-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0014_alter_rentpayment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='flag',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='payment',
            field=models.CharField(blank=True, default='payment', max_length=200),
        ),
    ]
