# Generated by Django 4.2.1 on 2023-05-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0015_rent_flag_alter_rentpayment_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentpayment',
            name='payment',
            field=models.CharField(blank=True, default='Bikash', max_length=200),
        ),
    ]
