# Generated by Django 3.2.7 on 2023-03-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('home_description', models.TextField()),
                ('rent_price', models.IntegerField()),
                ('total_square_feet', models.IntegerField()),
                ('total_washroom', models.IntegerField()),
                ('totla_bed', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('location', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong')], max_length=50)),
            ],
        ),
    ]
