# Generated by Django 3.2.7 on 2023-03-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AddField(
            model_name='rent',
            name='area',
            field=models.CharField(choices=[('Gec Moor', 'Gec Moor'), ('Chawkbazar', 'Chawkbazar'), ('mirpur', 'Mirpur')], default='', max_length=1000),
            preserve_default=False,
        ),
    ]
