# Generated by Django 3.2.7 on 2023-03-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230318_0725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rent',
        ),
    ]
