# Generated by Django 4.2.1 on 2023-05-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_delete_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentPurchaserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=300)),
                ('buyer_name', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=300)),
                ('division', models.CharField(max_length=300)),
                ('rent_price', models.CharField(max_length=300)),
                ('square_foot', models.CharField(max_length=300)),
                ('washroom', models.CharField(max_length=300)),
                ('bedroom', models.CharField(max_length=300)),
            ],
        ),
    ]
